# Generated by Django 4.2.6 on 2024-05-17 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JoinModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('address', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('age', models.CharField(choices=[('15-20', '15-20'), ('21-30', '21-30'), ('31-40', '31-40'), ('40+', '40+')], max_length=30)),
                ('gander', models.CharField(choices=[('Male', 'Male'), ('Famale', 'Famale'), ('Other', 'Other')], max_length=30)),
                ('status', models.CharField(choices=[('Student', 'Student'), ('Job', 'Job'), ('Unemployed', 'Unemployed'), ('Other', 'Other')], max_length=30)),
                ('laptob', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
